name: CI
on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - uses: coursier/cache-action@v6.3
      - uses: coursier/setup-action@v1.2.0-M3
        with:
          jvm: 8
      - run: ./mill -i __.test

  publish:
    needs: [tests]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: coursier/cache-action@v6.3
    - uses: coursier/setup-action@v1.2.0-M3
      with:
        jvm: 8
    - name: GPG setup
      run: .github/scripts/gpg-setup.sh
      env:
        PGP_SECRET: ${{ secrets.PUBLISH_SECRET_KEY }}
    - run: ./mill -i publishSonatype __.publishArtifacts
      env:
        PGP_PASSWORD: ${{ secrets.PUBLISH_SECRET_KEY_PASSWORD }}
        SONATYPE_PASSWORD: ${{ secrets.PUBLISH_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.PUBLISH_USER }}
